name:                metalborn-api
version:             0.1.0.0
github:              "tam-carre/metalborn"
license:             BSD3
author:              "Tam CARRE"
maintainer:          "Tam CARRE"
copyright:           "2022 Tam CARRE"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/tam-carre/metalborn#readme>

dependencies:
- base-noprelude
- relude
- hspec
- hspec-contrib
- servant
- servant-client
- http-client
- aeson
- http-conduit
- bytestring
- text
- vector
- containers
- lens
- lens-aeson
- mtl
- template-haskell
- time
- data-default
- base-unicode-symbols
- generic-lens
- extra
- random
- QuickCheck
- opaleye
- product-profunctors
- profunctors
- postgresql-simple
- safe-exceptions

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
  #- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  metalborn-api-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    dependencies:
    - metalborn-api

tests:
  metalborn-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - metalborn-api
